# This script takes the data objects generated by the kmedoids and lcga scripts and 
# performs some data wrangling operations in order to standardize them and to
# prepare them for presentation/publication. 

# For example, one thing this script does is standardize the cluster labels across 
# successive iterations of the same type op cluster algorithm. In this way, cluster A
# in the k = 2 model is the same cluster as cluster A in the k = 3 model. Cuz the algorithms
# don't do this automatically...




# SET-UP =======================================================================
# Libraries
library(dplyr)              # for data wrangling - everything else
library(tidyr)              # for data wrangling - stretching data, like wide/long
library(forcats)            # for wrangling with factors
library(readr)              # for reading and writing rds files
library(here)               # for relative pathways
library(lcmm)               # for LCGA
library(ggplot2)            # for data visualization
library(purrr)


# Load data
RCT_long <- read_rds(file =  here("1.data", "2.processed", "4.analyzed", "RCT_long.rds"))
load(file = here("1.data", "2.processed", "4.analyzed", "lcga7_new.RData"))


# Prep cluster data ---------------------------------------------------
# Assign cluster labels to respondents
# For LCGA and GMM_int, these need to be matched according to numeric_id or they will be mis-assigned
# LCGA
wide_dfs <- list(lcga1, lcga2, lcga3, lcga4, lcga5, lcga6, lcga7) %>%
  map(~ .x$pprob %>% select(numeric_id, class)) %>%
  set_names(paste0("lcga", 1:7)) %>%
  map2(names(.), ~ rename(.x, !!.y := class))

# Combine all dataframes in one go
RCT_long <- reduce(wide_dfs, left_join, by = "numeric_id", .init = RCT_long)




# Standardize cluster labels based on cluster visualization, script in exploration folder: Cluster_visualization.R
# Also, change the labels to a character rather than a number system because I find that less confusing
# LCGA
RCT_long$lcga1 <- recode(RCT_long$lcga1,
                    `1` = "A")
RCT_long$lcga2 <- recode(RCT_long$lcga2,
                    `1` = "A",
                    `2` = "B")
RCT_long$lcga3 <- recode(RCT_long$lcga3,
                    `1` = "A",
                    `2` = "B",
                    `3` = "C")
RCT_long$lcga4 <- recode(RCT_long$lcga4,
                    `1` = "A",
                    `2` = "B",
                    `3` = "C",
                    `4` = "D")
RCT_long$lcga5 <- recode(RCT_long$lcga5,
                    `1` = "A",
                    `2` = "B",
                    `3` = "C",
                    `4` = "D",
                    `5` = "E")
RCT_long$lcga6 <- recode(RCT_long$lcga6,
                    `1` = "E",
                    `2` = "A",
                    `3` = "C",
                    `4` = "B",
                    `5` = "D",
                    `6` = "F")
RCT_long$lcga7 <- recode(RCT_long$lcga7,
                    `1` = "F",
                    `2` = "E",
                    `3` = "D",
                    `4` = "A",
                    `5` = "G",
                    `6` = "C",
                    `7` = "B")

# Reorder lcga clusters cus they get jambled somehow
RCT_long$lcga2 <- factor(RCT_long$lcga2, 
                      levels = c("A", "B"))
RCT_long$lcga3 <- factor(RCT_long$lcga3, 
                      levels = c("A", "B", "C"))
RCT_long$lcga4 <- factor(RCT_long$lcga4, 
                      levels = c("A", "B", "C", "D"))
RCT_long$lcga5 <- factor(RCT_long$lcga5, 
                      levels = c("A", "B", "C", "D", "E"))
RCT_long$lcga6 <- factor(RCT_long$lcga6, 
                      levels = c("A", "B", "C", "D", "E", "F"))
RCT_long$lcga7 <- factor(RCT_long$lcga7, 
                      levels = c("A", "B", "C", "D", "E", "F", "G"))

# Save dataset
write_rds(RCT_long, file =  here("1.data", "2.processed", "4.analyzed", "RCT_wclusters.rds"))











