# This script takes the data objects generated by the kmedoids and lcga scripts and 
# performs some data wrangling operations in order to standardize them and to
# prepare them for presentation/publication. 

# For example, one thing this script does is standardize the cluster labels across 
# successive iterations of the same type op cluster algorithm. In this way, cluster A
# in the k = 2 model is the same cluster as cluster A in the k = 3 model. Cuz the algorithms
# don't do this automatically...




# SET-UP =======================================================================
# Libraries
library(dplyr)              # for data wrangling - everything else
library(tidyr)              # for data wrangling - stretching data, like wide/long
library(forcats)            # for wrangling with factors
library(readr)              # for reading and writing rds files
library(here)               # for relative pathways
library(lcmm)               # for LCGA
library(kml)                # for kmedoids
library(ggplot2)            # for data visualization
library(purrr)


# Load data
RCT_long <- read_rds(file =  here("1.data", "2.processed", "4.analyzed", "RCT_long.rds"))
load(file = here("1.data", "2.processed", "4.analyzed", "lcga7_new.RData"))
load(file = here("1.data", "2.processed", "4.analyzed", "gmm7_int_new.RData"))
load(file = here("1.data", "2.processed", "4.analyzed", "kmedoids_new.RData"))


# Prep cluster data ---------------------------------------------------

# Assign cluster labels to respondents
# For LCGA and GMM_int, these need to be matched according to numeric_id or they will be mis-assigned
# LCGA
wide_dfs <- list(lcga1, lcga2, lcga3, lcga4, lcga5, lcga6, lcga7) %>%
  map(~ .x$pprob %>% select(numeric_id, class)) %>%
  set_names(paste0("lcga", 1:7)) %>%
  map2(names(.), ~ rename(.x, !!.y := class))

# Combine all dataframes in one go
RCT_long <- reduce(wide_dfs, left_join, by = "numeric_id", .init = RCT_long)


# GMM_int
wide_dfs <- list(gmm_int1, gmm_int2, gmm_int3, gmm_int4, gmm_int5, gmm_int6, gmm_int7) %>%
  map(~ .x$pprob %>% select(numeric_id, class)) %>%
  set_names(paste0("gmm_int", 1:7)) %>%
  map2(names(.), ~ rename(.x, !!.y := class))

# Combine all dataframes in one go
RCT_long <- reduce(wide_dfs, left_join, by = "numeric_id", .init = RCT_long)


# Kmed cluster labels
RCT_clusters <- data.frame(
  respondent_id = unique(RCT_long$respondent_id),
  kclass2 = getClusters(cld_RCT4, 2),
  kclass3 = getClusters(cld_RCT4, 3),
  kclass4 = getClusters(cld_RCT4, 4),
  kclass5 = getClusters(cld_RCT4, 5),
  kclass6 = getClusters(cld_RCT4, 6),
  kclass7 = getClusters(cld_RCT4, 7)
)

# Verify that cluster labels were assigned to the right respondent ids
all(slot(cld_RCT4, "idAll") == RCT_clusters$respondent_id)

# Now merge with long data to transfer cluster labels
RCT_long <- RCT_long %>%
  left_join(RCT_clusters, by = "respondent_id")




# Standardize cluster labels based on cluster visualization, script in exploration folder: Cluster_visualization.R
# Also, change the labels to a character rather than a number system because I find that less confusing
# LCGA
RCT_long$lcga1 <- recode(RCT_long$lcga1,
                    `1` = "A")
RCT_long$lcga2 <- recode(RCT_long$lcga2,
                    `1` = "A",
                    `2` = "B")
RCT_long$lcga3 <- recode(RCT_long$lcga3,
                    `1` = "A",
                    `2` = "B",
                    `3` = "C")
RCT_long$lcga4 <- recode(RCT_long$lcga4,
                    `1` = "A",
                    `2` = "B",
                    `3` = "C",
                    `4` = "D")
RCT_long$lcga5 <- recode(RCT_long$lcga5,
                    `1` = "A",
                    `2` = "B",
                    `3` = "C",
                    `4` = "D",
                    `5` = "E")
RCT_long$lcga6 <- recode(RCT_long$lcga6,
                    `1` = "E",
                    `2` = "A",
                    `3` = "C",
                    `4` = "B",
                    `5` = "D",
                    `6` = "F")
RCT_long$lcga7 <- recode(RCT_long$lcga7,
                    `1` = "F",
                    `2` = "E",
                    `3` = "D",
                    `4` = "A",
                    `5` = "G",
                    `6` = "C",
                    `7` = "B")



# GMM_int
RCT_long$gmm_int1 <- recode(RCT_long$gmm_int1,
                    `1` = "A")
RCT_long$gmm_int2 <- recode(RCT_long$gmm_int2,
                    `1` = "B",
                    `2` = "A")
RCT_long$gmm_int3 <- recode(RCT_long$gmm_int3,
                    `1` = "A",
                    `2` = "B",
                    `3` = "C")
RCT_long$gmm_int4 <- recode(RCT_long$gmm_int4,
                    `1` = "C",
                    `2` = "D",
                    `3` = "A",
                    `4` = "B")
RCT_long$gmm_int5 <- recode(RCT_long$gmm_int5,
                    `1` = "D",
                    `2` = "A",
                    `3` = "B",
                    `4` = "C",
                    `5` = "E")
RCT_long$gmm_int6 <- recode(RCT_long$gmm_int6,
                    `1` = "A",
                    `2` = "B",
                    `3` = "C",
                    `4` = "E",
                    `5` = "D",
                    `6` = "F")
RCT_long$gmm_int7 <- recode(RCT_long$gmm_int7,
                    `1` = "F",
                    `2` = "B",
                    `3` = "C",
                    `4` = "D",
                    `5` = "A",
                    `6` = "G",
                    `7` = "E")

# Kmed
RCT_long$kclass2 <- recode(RCT_long$kclass2,
                      "A" = "B",
                      "B" = "A")
RCT_long$kclass3 <- recode(RCT_long$kclass3,
                      "A" = "C",
                      "B" = "A",
                      "C" = "B")
RCT_long$kclass4 <- recode(RCT_long$kclass4,
                      "A" = "C",
                      "B" = "D",
                      "C" = "A",
                      "D" = "B")
RCT_long$kclass5 <- recode(RCT_long$kclass5,
                      "A" = "C",
                      "B" = "E",
                      "C" = "D",
                      "D" = "B",
                      "E" = "A")
RCT_long$kclass6 <- recode(RCT_long$kclass6,
                      "A" = "C",
                      "B" = "E",
                      "C" = "D",
                      "D" = "B",
                      "E" = "A",
                      "F" = "F")
RCT_long$kclass7 <- recode(RCT_long$kclass7,
                      "A" = "E",
                      "B" = "C",
                      "C" = "D",
                      "D" = "F",
                      "E" = "A",
                      "F" = "B",
                      "G" = "G")


# Reorder lcga clusters cus they get jambled somehow
RCT_long$lcga2 <- factor(RCT_long$lcga2, 
                      levels = c("A", "B"))
RCT_long$lcga3 <- factor(RCT_long$lcga3, 
                      levels = c("A", "B", "C"))
RCT_long$lcga4 <- factor(RCT_long$lcga4, 
                      levels = c("A", "B", "C", "D"))
RCT_long$lcga5 <- factor(RCT_long$lcga5, 
                      levels = c("A", "B", "C", "D", "E"))
RCT_long$lcga6 <- factor(RCT_long$lcga6, 
                      levels = c("A", "B", "C", "D", "E", "F"))
RCT_long$lcga7 <- factor(RCT_long$lcga7, 
                      levels = c("A", "B", "C", "D", "E", "F", "G"))

# Reorder gmm_int clusters cus they get jambled somehow
RCT_long$gmm_int2 <- factor(RCT_long$gmm_int2, 
                    levels = c("A", "B"))
RCT_long$gmm_int3 <- factor(RCT_long$gmm_int3, 
                    levels = c("A", "B", "C"))
RCT_long$gmm_int4 <- factor(RCT_long$gmm_int4, 
                    levels = c("A", "B", "C", "D"))
RCT_long$gmm_int5 <- factor(RCT_long$gmm_int5, 
                    levels = c("A", "B", "C", "D", "E"))
RCT_long$gmm_int6 <- factor(RCT_long$gmm_int6, 
                    levels = c("A", "B", "C", "D", "E", "F"))
RCT_long$gmm_int7 <- factor(RCT_long$gmm_int7, 
                    levels = c("A", "B", "C", "D", "E", "F", "G"))

# Reorder kmed clusters cus they get jambled somehow
RCT_long$kclass2 <- factor(RCT_long$kclass2, 
                      levels = c("A", "B"))
RCT_long$kclass3 <- factor(RCT_long$kclass3, 
                      levels = c("A", "B", "C"))
RCT_long$kclass4 <- factor(RCT_long$kclass4, 
                      levels = c("A", "B", "C", "D"))
RCT_long$kclass5 <- factor(RCT_long$kclass5, 
                      levels = c("A", "B", "C", "D", "E"))
RCT_long$kclass6 <- factor(RCT_long$kclass6, 
                      levels = c("A", "B", "C", "D", "E", "F"))
RCT_long$kclass7 <- factor(RCT_long$kclass7, 
                      levels = c("A", "B", "C", "D", "E", "F", "G"))

# Save dataset
write_rds(RCT_long, file =  here("1.data", "2.processed", "4.analyzed", "RCT_wclusters.rds"))











